### ISSUE TITLE
daily build fails

### ISSUE THREAD

**Issue by javabeanz** [buschmais/jqassistant-sonar-plugin#1]
badge on github README page is showing build failed

**Comment by obfischer** [comment]
Thx for the issue. This repository is currently not used for the sonar plugin (but will be). The latest and greates version of the Sonar plugin can be found at the 1.1 branch of jQAssistant.

**Comment by javabeanz** [comment]
jqassistant github repo does not show branch 1.1, only master. It's a bit bad publicity if your daily build is broken.

**Comment by obfischer** [comment]
You can find the 1.1 branch here https://github.com/buschmais/jqassistant/tree/1.1

According the broken build: you are right. It hangs someware and is killed by Travis after 10 minutes. We will investigate why. Thx!
